core/solution/urls.py
from django.conf.urls.static import static
from django.urls import path

from core.solution.views.solution.views import *
from core.solution.views.solution_std.views import *
from core.solution.views.standardization_sln.views import *
from core.solution.views.standarization.views import StandardizationCreateView, StandardizationUpdateView

from luka import settings

app_name = 'solution'

urlpatterns = [
    path('add/', SolutionCreateView.as_view(), name='create_solution'),
    path('add_std/', SolutionStandardCreateView.as_view(), name='create_solution_std'),
    path('list/', SolutionListView.as_view(), name='list_solution'),
    path('list_std/', SolutionStdListView.as_view(), name='list_solution_std'),
    path('update/<uuid:pk>/', SolutionUpdateView.as_view(), name='update_solution'),
    path('detail/<uuid:pk>/', SolutionDetailView.as_view(), name='detail_solution'),
    path('detail_std/<uuid:pk>/', SolutionStdDetailView.as_view(), name='detail_solution_std'),
    path('add_solvent/<uuid:pk>/', SolutionAddSolventUpdateView.as_view(), name='add_solvent_solution'),
    path('add_solvent_std/<uuid:pk>/', SolutionStdAddSolventUpdateView.as_view(), name='add_solvent_solution_std'),
    path('solution_label/<uuid:pk>/', SolutionLabelPDFDetailView.as_view(), name='solution_label_pdf'),
    path('solution_label_std/<uuid:pk>/', SolutionStdLabelPDFDetailView.as_view(), name='solution_label_std_pdf'),
    path('api/inventory-reagent/<uuid:reagent_id>/', get_inventory_reagent_data, name='inventory_reagent_data'),
    path('add_standardization/<uuid:pk>/', StandardizationCreateView.as_view(), name='create_standardization'),
    path('update_standardization/<uuid:pk>/', StandardizationUpdateView.as_view(), name='update_standardization'),
    path('add_standardization_sln/<uuid:pk>/', StandardizationSolutionCreateView.as_view(),
         name='create_standardization_solution'),
    path('delete_standardization_sln/<uuid:pk>/', StandardizationSolutionDeleteView.as_view(),
         name='delete_standardization_solution'),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

core/user/urls.py
from django.conf.urls.static import static
from django.urls import path

from core.user.views.training.views import *
from core.user.views.competence.views import *
from luka import settings
from core.user.views.user.views import *

app_name = 'user'

urlpatterns = [
    path('add/', UserCreateView.as_view(), name='user_create'),
    path('list/', UserListView.as_view(), name='user_list'),
    path('update-admin/<str:slug>/', UserUpdateAdminView.as_view(), name='user_update_admin'),
    path('update-user/<str:slug>/', UserUpdateView.as_view(), name='user_update_user'),
    path('update-password/<str:slug>/', UserPasswordUpdateView.as_view(), name='user_password_update'),
    path('detail/<str:slug>/', UserDetailView.as_view(), name='user_detail'),
    path('edit/password/', UserChangePasswordView.as_view(), name='change_password'),
    path('training/add/<uuid:pk>/', TrainingCreateView.as_view(), name='create_training'),
    path('training/add_update/<uuid:pk>/', TrainingCreateUpdateView.as_view(), name='create_update_training'),
    path('training/update/<uuid:pk>/', TrainingUpdateView.as_view(), name='update_training'),
    path('training/delete/<uuid:pk>/', TrainingDeleteView.as_view(), name='delete_training'),
    path('training/download/', TrainingDownloadView.as_view(), name='download_training'),
    path('competence/add/<uuid:pk>/', CompetenceCreateView.as_view(), name='create_competence'),
    path('competence/update/<uuid:pk>/', CompetenceUpdateView.as_view(), name='update_competence'),
    path('competence/delete/<uuid:pk>/', CompetenceDeleteView.as_view(), name='delete_competence'),
    path('competence/download/', CompetenceDownloadView.as_view(), name='download_competence'),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

luka/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.home.views import HomeView
from luka import settings as setting, settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", HomeView.as_view(), name='home'),
    path('user/', include('core.user.urls')),
    path('start/', include('core.start.urls')),
    path('login/', include('core.login.urls')),
    path('company/', include('core.company.urls')),
    path('reagent/', include('core.reagent.urls')),
    path('solution/', include('core.solution.urls')),
    path('laboratory/', include('core.laboratory.urls')),
    path('equipment/', include('core.equipment.urls')),
    # path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if setting.DEBUG:
    urlpatterns += static(setting.MEDIA_URL, document_root=setting.MEDIA_ROOT)

core/solution/views.py
import os
from urllib.request import urlopen

import boto3
from botocore.config import Config
from botocore.exceptions import ClientError
from decouple import config
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect
from django.template.loader import get_template
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView, ListView, UpdateView, DetailView
from xhtml2pdf import pisa

from core.company.models import Company
from core.mixins import ValidatePermissionRequiredMixin
from core.solution.forms import *
from core.solution.models import Solution
from luka import settings


# Creación de Soluciones
class SolutionCreateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, CreateView):
    model = Solution
    form_class = SolutionForm
    template_name = 'create_three.html'
    permission_required = 'reagent.add_reagent'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        self.object = None
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()
                if form.is_valid():
                    self.object = form.save()
                    code_solution = form.cleaned_data.get('code_solution')
                    messages.success(request, f'Solución "{code_solution}" creada satisfactoriamente!')
                    # Provide redirect URL to detail view for AJAX to use
                    data['redirect_url'] = self.get_success_url()
                else:
                    messages.error(request, form.errors)
                    data['error'] = str(form.errors)
            else:
                data['error'] = 'No ha ingresado datos en los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_success_url(self):
        return reverse('solution:detail_solution', kwargs={'pk': self.object.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Preparar Solución'
        context['action'] = 'add'
        context['entity'] = 'Preparar Solución'
        context['div'] = '10'
        context['icon'] = 'fa-solid fa-flask-vial'
        # Fallback cancel/back link to the solutions list
        try:
            context['list_url'] = reverse_lazy('solution:list_solution')
        except Exception:
            pass
        return context


# Listado de Soluciones
class SolutionListView(LoginRequiredMixin, ValidatePermissionRequiredMixin, ListView):
    model = Solution
    template_name = 'list_solution.html'
    permission_required = 'reagent.view_reagent'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchdata':
                reagents = list(Solution.objects.select_related('solute_reagent__reagent', 'preparated_by').values(
                    'id',
                    'solute_reagent__reagent__description_reagent',
                    'code_solution',
                    'concentration',
                    'concentration_unit',
                    'preparation_date',
                    'expire_date_solution',
                    'quantity_solution',
                    'preparated_by__first_name',
                    'preparated_by__last_name',
                    'preparated_by__cargo',
                    'preparated_by',
                ).order_by('-code_solution'))

                # Formatear el nombre completo
                for reagent in reagents:
                    first_name = reagent.get('preparated_by__first_name', '') or ''
                    last_name = reagent.get('preparated_by__last_name', '') or ''
                    cargo = reagent.get('preparated_by__cargo', '') or ''
                    reagent['preparated_by__get_full_name'] = f"{first_name} {last_name}, {cargo}".strip()

                return JsonResponse(reagents, safe=False)
            else:
                data['error'] = 'Ha ocurrido un error'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Soluciones'
        context['create_url'] = reverse_lazy('solution:create_solution')
        context['entity'] = 'Soluciones'
        context['div'] = '12'
        context['icon'] = 'fa-solid fa-flask-vial'
        return context


# Edición de Soluciones
class SolutionUpdateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, UpdateView):
    model = Solution
    form_class = SolutionForm
    template_name = 'update_solution.html'
    permission_required = 'reagent.change_reagent'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                if form.is_valid():
                    self.object = form.save()
                    code_solution = form.cleaned_data.get('code_solution')
                    messages.success(request, f'Solución "{code_solution}" editada satisfactoriamente!')
                else:
                    messages.error(request, form.errors)
                return redirect(self.get_context_data()['list_url'])
            else:
                data['error'] = 'No ha ingresado datos en los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Editar Solución a Preparar'
        context['entity'] = 'Editar Solución a Preparar'
        context['action'] = 'edit'
        context['div'] = '10'
        context['icon'] = 'fa-solid fa-flask-vial'
        context['list_url'] = reverse_lazy('solution:detail_solution', kwargs={'pk': self.object.pk})
        return context


# Adición de Solvente
class SolutionAddSolventUpdateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, UpdateView):
    model = Solution
    form_class = SolutionAddSolventForm
    template_name = 'create_solvent.html'
    permission_required = 'reagent.add_reagent'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                if form.is_valid():
                    form.save()
                    messages.success(request, f'Solvente Añadido satisfactoriamente!')
                else:
                    messages.error(request, form.errors)
            else:
                data['error'] = 'No ha ingresado datos en los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['entity'] = 'Adición de Solvente'
        context['action'] = 'edit'
        context['class'] = 'col-md-6'
        context['info_form'] = self.object.solvent_reagent.reagent.description_reagent + ' al ' + str(self.object.solvent_reagent.purity) + self.object.solvent_reagent.reagent.purity_unit
        return context


# Detalle de Soluciones
class SolutionDetailView(LoginRequiredMixin, ValidatePermissionRequiredMixin, DetailView):
    model = Solution
    template_name = 'detail_solution.html'
    permission_required = 'reagent.add_reagent'

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    # def get_queryset(self):
    #     now = timezone.now()
    #     Training.objects.filter(
    #         training_status='Vigente',
    #         date_training_expire__lte=now
    #     ).update(training_status='Vencido')
    #     return super(UserDetailView, self).get_queryset()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Preparación de Solución'
        context['entity'] = 'Preparación de Solución'
        context['label_url'] = reverse_lazy('solution:solution_label_pdf', kwargs={'pk': self.object.pk})
        # if self.request.user.has_perm('user.add_user'):
        #     context['back'] = reverse_lazy('user:user_list')
        context['icon'] = 'fa-solid fa-flask-vial'
        context['list_url'] = reverse_lazy('solution:list_solution')
        context['update_solution'] = reverse_lazy('solution:update_solution', kwargs={'pk': self.object.pk})
        return context


# Etiqueta de Identificación de Solución
class SolutionLabelPDFDetailView(LoginRequiredMixin, ValidatePermissionRequiredMixin, View):
    permission_required = 'reagent.add_reagent'

    @staticmethod
    def link_callback(uri, rel):

        # use short variable names
        sUrl = settings.STATIC_URL  # Typically /static/

core/solution/templates/solution_std/create_solution_std.html
{% extends 'create_three.html' %}

core/solution/templates/solution_std/detail_solution_std.html
{% extends 'body.html' %}
{% load static %}
{% load widget_tweaks %}
{% load humanize %}
{% load l10n %}


{% block head %}
    {% block head_list %}
        <style>
            /* Ajustes para la tabla con id data_0 */
            #data_0, #data_0 th, #data_0 td {
                font-size: 0.85rem;
            }

            #data_0 thead th {
                text-align: center;
                vertical-align: middle;
            }
        </style>
    {% endblock %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-11">
            <div class="tile">
                <div class="tile-title">
                    <h3 class="title">
                        {% if object.solute_std.reagent.umb == 'g' %}
                            Solución Estándar
                        {% endif %}
                        {{ object.solute_std.reagent.description_reagent }} {{ object.concentration_std | unlocalize }}
                        {{ object.concentration_unit }} <span class="m-4">{{ object.code_solution_std }}</span>
                    </h3>
                </div>
                <div class="tile-body">
                    <div class="row">
                        <div class="col-md-2">
                            <b>Cantidad {% if not object.solute_std.reagent.ready_to_use %}a Preparar{% endif %}</b><br>
                            <p>{{ object.quantity_solution_std | intcomma:False }} mL</p>
                        </div>
                        <div class="col-md-2">
                            <b>Concentración</b><br>
                            <p>{{ object.concentration_std | unlocalize }} {{ object.concentration_unit }}</p>
                        </div>
                        <div class="col-md-5">
                            <b>Reactivo</b><br>
                            <p><b class="text-danger">
                                {% if object.solute_std.reagent.ready_to_use %}
                                    Solución Estándar lista para Usar
                                {% else %}
                                    {{ object.quantity_std | unlocalize }} {{ object.solute_std.reagent.umb }}
                                {% endif %}
                            </b>
                                {% if not object.solute_std.reagent.ready_to_use %}
                                    de {{ object.solute_std.reagent.description_reagent }} al
                                    {{ object.solute_std.purity }}{{ object.solute_std.reagent.purity_unit }}
                                {% endif %}
                            </p>
                        </div>
                        <div class="col-md-2">
                            <b>N° de Lote</b>
                            <p>{{ object.solute_std.batch_number }}</p>
                        </div>
                        {% if not object.solute_std.reagent.ready_to_use %}
                            <div class="col-md-4">
                                <b>Solvente</b><br>
                                <p>
                                    {% if object.quantity_solvent %}
                                        {{ object.quantity_solvent | unlocalize }}
                                        {{ object.solvent_reagent.reagent.umb }} de
                                    {% endif %}
                                    {{ object.solvent_reagent.reagent.description_reagent }}
                                    {% if not object.solvent_reagent.purity == 100 %}
                                        {{ object.solvent_reagent.purity }}{{ object.solvent_reagent.reagent.purity_unit }}
                                        ,
                                    {% endif %}
                                    Lote N°: {{ object.solvent_reagent.batch_number }}
                                </p>
                            </div>
                        {% endif %}
                    </div>
                    {% if object.quantity_solvent or object.solute_std.reagent.ready_to_use %}
                        <div class="row mt-1">
                            <div class="col-md-4">
                                <b>Preparado por </b><br>
                                <p>{{ object.preparated_std_by }}</p>
                            </div>
                            <div class="col-md-3">
                                <b>Fecha de Preparación</b><br>
                                <p>{{ object.preparation_std_date | date:'Y-m-d' }}</p>
                            </div>
                            <div class="col-md-3">
                                <b>Vencimiento</b><br>
                                <p>{{ object.expire_std_date_solution | date:'Y-m-d' }}</p>
                            </div>
                        </div>
                    {% endif %}
                </div>
                <div class="tile-footer">
                    {% if not object.quantity_solvent and not object.solute_std.reagent.ready_to_use %}
                        {% if object.quantity_std < object.solute_std.quantity_stock %}
                            <button onclick="open_modal('{% url 'solution:add_solvent_solution_std' object.id %}')"
                                    class="btn btn-primary me-2">
                                <i class="bi bi-moisture me-2"></i> Añadir de Solvente
                            </button>
                        {% else %}
                                <p class="text-danger p-2">Cantidad de Reactivo requerida mayor que la
                                    disponible {{ object.solute_std.quantity_stock | unlocalize }} {{ object.solute_std.reagent.umb }}</p>
                        {% endif %}
                    {% endif %}
                    <a href="{{ label_url }}" type="button" class="btn btn-danger me-2" target="_blank">
                        <i class="fa fa-fw fa-lg fa-ticket me-2"></i> Etiqueta
                    </a>
                    {% if list_url %}
                        <a href="{{ list_url }}" class="btn btn-secondary me-2">
                            <i class="fa fa-fw fa-lg fa-list me-2"></i>Soluciones Estándar
                        </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% if transactions %}
        <div class="row">
            <div class="col-md-10">
                <div class="tile mb-3">
                    <div class="tile-title">
                        <h3 class="title">Detalle Consumo</h3>
                    </div>
                    <div class="tile-body">
                        <div class="table-responsive">
                            <table class="table table-hover table-bordered" id="data_0">
                                <thead>
                                <tr>
                                    <th style="width:10%">Fecha</th>
                                    <th style="width:15%">Tipo</th>
                                    <th style="width:10%">Cant. ({{ object.solute_std.reagent.umb }})</th>
                                    <th style="width:25%">Realizada por</th>
                                    <th style="width:30%">Detalle</th>
                                    <th style="width:10%">Acciones</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for foo in transactions %}
                                    <tr>
                                        <td>{{ foo.date_transaction | date:'Y-m-d' }}</td>
                                        <td>{{ foo.type_transaction }}</td>
                                        <td>{{ foo.quantity | intcomma:False }}</td>
                                        <td>{{ foo.user_transaction }}</td>
                                        <td>{{ foo.detail_transaction }}</td>
                                        <td>
                                            <a onclick="open_modal('{% url 'user:update_training' foo.id %}')"
                                               title="Editar">
                                                <i class="bi bi-pencil-square text-warning me-2"></i>
                                            </a>
                                            <a onclick="open_modal('{% url 'user:delete_training' foo.id %}')"
                                               title="Eliminar">
                                                <i class="bi bi-trash text-danger me-2"></i>
                                            </a>
                                            {% if foo.training_status == 'Vencido' %}
                                                <a onclick="open_modal('{% url 'user:create_update_training' foo.id %}')"
                                                   title="Actualizar">
                                                    <i class="bi bi-arrow-clockwise text-info me-2"></i>
                                                </a>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% empty %}
                                    <tr>
                                        <td colspan="6" class="text-center">
                                            No hay capacitaciones asociadas.
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block scripts_detail %}
    <!-- Data table plugin-->
    <script src="{% static 'lib/vali-admin/js/plugins/jquery.dataTables.min.js' %}"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/v/bs5/dt-1.13.4/datatables.min.css">

    <script>

        try {
            $(function () {
                // Solo inicializar DataTable si hay filas de datos
                const hasData = $('#data_0 tbody tr').length > 0 && !$('#data_0 tbody tr td[colspan]').length;

                if (hasData) {
                    $('#data_0').DataTable({
                        responsive: true,
                        autoWidth: false,
                        searching: false,
                        info: false,
                        order: [[3, 'desc']],
                        language: {
                            url: "//cdn.datatables.net/plug-ins/1.10.21/i18n/Spanish.json"
                        },
                        columnDefs: [
                            {
                                targets: [1, 5],
                                className: 'td-actions text-center',
                                orderable: false,
                            },
                            {
                                targets: [2, 3, 4],
                                className: 'td-actions text-center',
                            }
                        ]
                    });
                } else {
                    console.info('DataTable no inicializado: tabla vacía o sin datos válidos');
                }
            })
        } catch (error) {
            console.error('Error al inicializar DataTable:', error);
        }

    </script>

{% endblock %}

core/solution/templates/solution_std/label_solution_std.html
{#{% extends 'label_pdf.html' %}#}
{#{% load humanize %}#}
{#{% load l10n %}#}
{##}
{#{% block content_pdf %}#}
{##}
{#    <table class="table">#}
{#        <tr>#}
{#            <td>#}
{#                <h5>#}
{#                    <b>#}
{#                        {{ std.solute_std.reagent.description_reagent }}#}
{#                        {{ std.concentration_std }}{{ std.concentration_unit }}#}
{#                    </b>#}
{#                </h5>#}
{#            </td>#}
{#        </tr>#}
{#    </table>#}
{##}
{#    <table class="tabContent" style="border-radius: 15px">#}
{#        <tr style="border-bottom: none; padding-bottom: 1px">#}
{#            <th style="border: none"><strong>Código: </strong></th>#}
{#            <th style="border: none"><strong>Preparación: </strong></th>#}
{#            <th style="border: none"><strong>Volumen: </strong></th>#}
{#            <th style="border: none"><strong>Vence: </strong></th>#}
{#        </tr>#}
{#        <tr style="border-top: none; border-bottom: none">#}
{#            <td style="border: none">{{ std.code_solution_std }}</td>#}
{#            <td style="border: none">{{ std.preparation_std_date | date:'Y-m-d' }}</td>#}
{#            <td style="border: none">{{ std.quantity_solution_std | intcomma:False }}mL</td>#}
{#            <td style="border: none">{{ std.expire_std_date_solution | date:'Y-m-d' }}</td>#}
{#        </tr>#}
{#        <tr style="border-bottom: none; border-top: none">#}
{#            <th style="border: none" colspan="2"><strong>Preparado por:</strong></th>#}
{#        </tr>#}
{#        <tr style="border-top: none">#}
{#            <td style="border: none" colspan="2">{{ std.preparated_std_by }}</td>#}
{#        </tr>#}
{#    </table>#}
{##}
{#{% endblock %}#}

{% extends 'label_pdf.html' %}
{% load humanize %}
{% load l10n %}

{% block content_pdf %}

    <table style="width: 100%; margin-bottom: 10px;">
        <tr>
            <td style="vertical-align: top;">
                {% if company_logo_path %}
                    <img src="{{ company_logo_path }}" alt="Logo {{ company.company_name }}"
                         style="width: 150px; height: auto;">
                {% else %}
                    <p style="font-size: 12px; color: #666;">{{ company.company_name }}</p>
                {% endif %}
            </td>
            <td style="vertical-align: top; padding-left: 15px;">
                <table style="width: 100%;">
                    <tr>
                        <td style="margin: 0; padding: 15px 0 0;">
                            <b style="font-size: 13px;">{{ sln.code_solution_std }}</b>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>

    <table class="table" style="margin-bottom: 5px;">
        <tr>
            <td style="text-align: center; vertical-align: middle; padding-top: 10px">
                <h5 style="margin: 0; padding: 0; text-align: center;">
                    <b>
                        {% if sln.solute_std.reagent.umb == 'g' %}Solución de {% endif %}{{ sln.solute_std.reagent.description_reagent }}
                        {{ sln.concentration_std }}{{ sln.concentration_unit }}
                    </b>
                </h5>
            </td>
        </tr>
    </table>

    <table class="tabContent" style="border-radius: 15px; width: 100%;">
        <tr style="border-bottom: none; padding-bottom: 1px">
            <th style="border: none; padding: 2px 5px 0;"><strong>Preparación:</strong></th>
            <th style="border: none; padding: 2px 5px 0;"><strong>Volumen:</strong></th>
            <th style="border: none; padding: 2px 5px 0;"><strong>Vence:</strong></th>
        </tr>
        <tr style="border-bottom: none; border-top:none; padding-bottom: 1px">
            <td style="border: none; padding: 0 5px 3px;">{{ sln.preparation_std_date|date:'Y-m-d' }}</td>
            <td style="border: none; padding: 0 5px 3px;">{{ sln.quantity_solution_std|intcomma:False }}mL</td>
            <td style="border: none; padding: 0 5px 3px;">{{ sln.expire_std_date_solution|date:'Y-m-d' }}</td>
        </tr>
        <tr style="border-bottom: none; border-top:none; padding-bottom: 1px">
            <th style="border: none; padding: 2px 5px 0;"><strong>N° de Lote:</strong></th>
        </tr>
        <tr style="border-bottom: none; border-top:none; padding-bottom: 1px">
            <td style="border: none; padding: 0 5px 3px;">{{ sln.solute_std.batch_number }}</td>
        </tr>
        <tr style="border-bottom: none; border-top:none; padding-bottom: 1px">
            <th style="border: none; padding: 2px 5px 0;" colspan="3"><strong>Preparado por:</strong></th>
        </tr>
        <tr style="border-top:none; padding-bottom: 1px">
            <td style="border: none; padding: 0 5px;" colspan="3">{{ sln.preparated_std_by }}</td>
        </tr>
    </table>

{% endblock %}