core/company/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from core.company.views.company.views import *
from core.company.views.process.views import *
from core.company.views.sample_point.views import *
from core.company.views.site.views import *
from core.company.views.stage.views import *

app_name = 'company'

urlpatterns = [
    # Company
    path('add/', CompanyCreateView.as_view(), name='company_create'),
    path('update/<uuid:pk>/', CompanyUpdateView.as_view(), name='company_update'),
    path('detail/<uuid:pk>/', CompanyDetailView.as_view(), name='company_detail'),
    # Plantas
    path('add_site/', SiteCreateView.as_view(), name='create_site'),
    path('update_site/<uuid:pk>/', SiteUpdateView.as_view(), name='update_site'),
    path('detail_site/<uuid:pk>/', SiteDetailView.as_view(), name='detail_site'),
    # Procesos
    path('add_process/<uuid:pk>/', ProcessCreateView.as_view(), name='create_process'),
    path('update_process/<uuid:pk>/', ProcessUpdateView.as_view(), name='update_process'),
    # Etapas
    path('add_stage/<uuid:pk>/', StageCreateView.as_view(), name='create_stage'),
    path('update_stage/<uuid:pk>/', StageUpdateView.as_view(), name='update_stage'),
    # Puntos de Muestreo
    path('add_sample_point/<uuid:pk>/', SamplePointCreateView.as_view(), name='create_sample_point'),
    path('update_sample_point/<uuid:pk>/', SamplePointUpdateView.as_view(), name='update_sample_point')
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

luka/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.home.views import HomeView
from luka import settings as setting, settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", HomeView.as_view(), name='home'),
    path('user/', include('core.user.urls')),
    path('start/', include('core.start.urls')),
    path('login/', include('core.login.urls')),
    path('company/', include('core.company.urls')),
    path('reagent/', include('core.reagent.urls')),
    path('solution/', include('core.solution.urls')),
    path('laboratory/', include('core.laboratory.urls')),
    path('equipment/', include('core.equipment.urls')),
    # path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if setting.DEBUG:
    urlpatterns += static(setting.MEDIA_URL, document_root=setting.MEDIA_ROOT)

core/company/views/company/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.http import JsonResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DetailView

from core.company.forms import *
from core.company.models import *
from core.mixins import ValidatePermissionRequiredMixin


# Creación de Empresa
class CompanyCreateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, CreateView):
    model = Company
    form_class = CompanyForm
    template_name = 'company/create_company.html'
    permission_required = 'company.add_company'

    def dispatch(self, request, *args, **kwargs):
        self.object = None
        try:
            if Company.objects.exists():
                company = Company.objects.first()
                return redirect('company:company_detail', pk=company.id)
        except ObjectDoesNotExist:
            pass
        return super(CompanyCreateView, self).dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()
                if form.is_valid():
                    form.save()
                    messages.success(request, f'Empresa configurada satisfactoriamente!')
                else:
                    messages.error(request, form.errors)
            else:
                data['error'] = 'No ha ingresado datos en los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Perfil Empresa'
        context['entity'] = 'Perfil Empresa'
        context['action'] = 'add'
        context['div'] = '10'
        context['list_url'] = reverse_lazy('start:start')
        context['icon'] = 'bi bi-building-fill-add'
        return context


# Edición de Empresa
class CompanyUpdateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, UpdateView):
    model = Company
    form_class = CompanyForm
    template_name = 'company/create_company.html'
    permission_required = 'company.change_company'

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                if form.is_valid():
                    form.save()
                    messages.success(request, f'La Empresa se ha editado satisfactoriamente!')
                    # Return a direct redirect response instead of relying on client-side redirection
                    return redirect(self.get_context_data()['list_url'])
                else:
                    messages.error(request, form.errors)
                    data['error'] = form.errors
            else:
                data['error'] = 'No ha editado los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Editar Empresa'
        context['entity'] = 'Editar Información Empresa'
        context['action'] = 'edit'
        context['div'] = '10'
        context['list_url'] = reverse_lazy('company:company_detail', kwargs={'pk': self.kwargs['pk']})
        context['icon'] = 'bi bi-buildings-fill'
        return context


# Detalle de empresa por administrador
class CompanyDetailView(LoginRequiredMixin, ValidatePermissionRequiredMixin, DetailView):
    model = Company
    template_name = 'company/detail_company.html'
    permission_required = 'user.change_user'

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return super(CompanyDetailView, self).get_queryset()

    def logo(self):
        try:
            return Company.objects.first().get_logo()
        except ObjectDoesNotExist:
            return '{}{}'.format(STATIC_URL, 'img/empty.png')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Empresa'
        context['entity'] = 'Empresa'
        context['sites'] = Site.objects.filter(company_id=self.object.id)
        context['icon'] = 'bi bi-buildings-fill'
        context['company_logo'] = self.logo()
        return context

core/company/views/process/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView, UpdateView

from core.company.forms import ProcessForm, ProcessUpdateForm
from core.company.models import Process, Site
from core.mixins import ValidatePermissionRequiredMixin


# Creación de Proceso
class ProcessCreateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, CreateView):
    model = Process
    form_class = ProcessForm
    template_name = 'process/create_process.html'
    permission_required = 'company.add_company'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        self.object = None
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()
                if form.is_valid():
                    form.save()
                    messages.success(request, f'Proceso creado satisfactoriamente!')
                else:
                    messages.error(request, form.errors)
            else:
                data['error'] = 'No ha ingresado datos en los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'site': Site.objects.get(pk=self.kwargs.get('pk'))})
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action'] = 'add'
        context['entity'] = 'Creación de Proceso'
        context['class'] = 'col-md-8'
        return context


# Edición de Proceso
class ProcessUpdateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, UpdateView):
    model = Process
    form_class = ProcessUpdateForm
    template_name = 'process/create_process.html'
    permission_required = 'company.add_company'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                if form.is_valid():
                    form.save()
                    messages.success(request, f'Proceso editado satisfactoriamente!')
                else:
                    messages.error(request, form.errors)
                # return redirect(self.get_context_data()['list_url'])
            else:
                data['error'] = 'No ha ingresado datos en los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['entity'] = 'Edición de Proceso'
        context['action'] = 'edit'
        return context

core/company/views/sample_point/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView, UpdateView

from core.company.forms import SamplePointForm, SamplePointUpdateForm
from core.company.models import SamplePoint, Site
from core.mixins import ValidatePermissionRequiredMixin


# Creación de Puntos de Muestreo
class SamplePointCreateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, CreateView):
    model = SamplePoint
    form_class = SamplePointForm
    template_name = 'sample_point/create_sample_point.html'
    permission_required = 'company.add_company'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        self.object = None
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()
                if form.is_valid():
                    form.save()
                    messages.success(request, f'Punto de Muestreo creado satisfactoriamente!')
                else:
                    messages.error(request, 'Por favor corrija los errores: {}'.format(form.errors.as_json()))
            else:
                data['error'] = 'No ha ingresado datos en los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        site = Site.objects.get(pk=self.kwargs.get('pk'))
        kwargs.update({'site': site})
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action'] = 'add'
        context['entity'] = 'Creación de Punto de Muestreo'
        return context


# Edición de Puntos de Muestreo
class SamplePointUpdateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, UpdateView):
    model = SamplePoint
    form_class = SamplePointUpdateForm
    template_name = 'sample_point/create_sample_point.html'
    permission_required = 'company.add_company'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                if form.is_valid():
                    form.save()
                    messages.success(request, f'Punto de Muestreo editado satisfactoriamente!')
                else:
                    messages.error(request, 'Por favor corrija los errores: {}'.format(form.errors.as_json()))
            else:
                data['error'] = 'No ha ingresado datos en los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        sample = SamplePoint.objects.get(pk=self.kwargs.get('pk'))
        kwargs.update({'sample': sample})
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['entity'] = 'Edición de Punto de Muestreo'
        context['action'] = 'edit'
        return context

core/company/views/stage/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView, UpdateView

from core.company.forms import StageForm, StageUpdateForm
from core.company.models import Stage, Site
from core.mixins import ValidatePermissionRequiredMixin


# Creación de Etapas
class StageCreateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, CreateView):
    model = Stage
    form_class = StageForm
    template_name = 'stage/create_stage.html'
    permission_required = 'company.add_company'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        self.object = None
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()
                if form.is_valid():
                    form.save()
                    messages.success(request, f'Etapa creada satisfactoriamente!')
                else:
                    messages.error(request, 'Por favor corrija los errores: {}'.format(form.errors.as_json()))
            else:
                data['error'] = 'No ha ingresado datos en los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        site = Site.objects.get(pk=self.kwargs.get('pk'))
        kwargs.update({'site': site})
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action'] = 'add'
        context['entity'] = 'Creación de Etapa'
        return context


# Edición de Etapa
class StageUpdateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, UpdateView):
    model = Stage
    form_class = StageUpdateForm
    template_name = 'stage/create_stage.html'
    permission_required = 'company.add_company'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                if form.is_valid():
                    form.save()
                    messages.success(request, f'Etapa editada satisfactoriamente!')
                else:
                    messages.error(request, 'Por favor corrija los errores: {}'.format(form.errors.as_json()))
            else:
                data['error'] = 'No ha ingresado datos en los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        stage = Stage.objects.get(pk=self.kwargs.get('pk'))
        kwargs.update({'stage': stage})
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['entity'] = 'Edición de Etapa'
        context['action'] = 'edit'
        return context

core/company/templates/company/create_company.html
{% extends 'create_two.html' %}

core/company/templates/company/detail_company.html
{% extends 'body.html' %}
{% load static %}

{% block head %}

    {% block head_list %}

    {% endblock %}

{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-8">
            <div class="tile">
                <section class="invoice">
                    <div class="row mb-4">
                        <div class="col-6">
                            <h2 class="page-header">{{ object.company_name }}</h2>
                        </div>
                    </div>
                    <div class="row invoice-info">
                        <div class="col-4">
                            <img src="{{ company_logo }}" alt="Company Logo" class="img-fluid">
                        </div>
                        <div class="col-md-4">
                            <address>
                                <strong>NIT</strong>
                                {{ object.company_nit }}
                                <br>
                                <strong>Dirección</strong>
                                {{ object.company_address }}
                                <br>
                                {{ object.company_city }}, {{ object.company_country }}
                                <br>
                            </address>
                        </div>
                        <div class="col-md-4">
                            <address>
                                <strong>Alerta Capacitaciones</strong>
                                {{ object.training_alert }} días
                                <br>
                            </address>
                        </div>
                    </div>
                    <br>
                    <h3 class="tile-title">Sites</h3>
                    <div class="row">
                        <div class="col-12 table-responsive">
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th>Planta</th>
                                    <th>Dirección</th>
                                    <th>Ciudad</th>
                                    <th>País</th>
                                    <th>Estado</th>
                                    <th>Acciones</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for site in sites %}
                                    <tr>
                                        <td>{{ site.site_name }}</td>
                                        <td>{{ site.site_address }}</td>
                                        <td>{{ site.site_city }}</td>
                                        <td>{{ site.site_country }}</td>
                                        <td>
                                            {% if site.site_enable %}
                                                <span class="badge bg-success">Activo</span>
                                            {% else %}
                                                <span class="badge bg-danger">Inactivo</span>
                                            {% endif %}
                                        </td>
                                        <td>
                                            <a href="{% url 'company:update_site' site.id %}" type="button">
                                                <i class="bi bi-pencil-square text-warning me-2"></i>
                                            </a>
                                            <a href="{% url 'company:detail_site' site.id %}" type="button">
                                                <i class="bi bi-info-square text-info"></i>
                                            </a>
                                        </td>
                                    </tr>
                                {% empty %}
                                    <tr>
                                        <td colspan="5" class="text-center">No hay sites disponibles.</td>
                                    </tr>
                                {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="row d-print-none mt-2">
                        <div class="col-12 text-end">
                            <a class="btn btn-primary" href="{% url 'company:create_site' %}"><i
                                class="bi bi-plus-circle me-2"></i> Nuevo Site</a>
                            <a class="btn btn-outline-primary" href="{% url 'company:company_update' object.id %}"><i
                                class="bi bi-pencil-square me-2"></i> Editar</a>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
{% endblock %}