core/company/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from core.company.views.company.views import *
from core.company.views.process.views import *
from core.company.views.sample_point.views import *
from core.company.views.site.views import *
from core.company.views.stage.views import *

app_name = 'company'

urlpatterns = [
    # Company
    path('add/', CompanyCreateView.as_view(), name='company_create'),
    path('update/<uuid:pk>/', CompanyUpdateView.as_view(), name='company_update'),
    path('detail/<uuid:pk>/', CompanyDetailView.as_view(), name='company_detail'),
    # Plantas
    path('add_site/', SiteCreateView.as_view(), name='create_site'),
    path('update_site/<uuid:pk>/', SiteUpdateView.as_view(), name='update_site'),
    path('detail_site/<uuid:pk>/', SiteDetailView.as_view(), name='detail_site'),
    # Procesos
    path('add_process/<uuid:pk>/', ProcessCreateView.as_view(), name='create_process'),
    path('update_process/<uuid:pk>/', ProcessUpdateView.as_view(), name='update_process'),
    # Etapas
    path('add_stage/<uuid:pk>/', StageCreateView.as_view(), name='create_stage'),
    path('update_stage/<uuid:pk>/', StageUpdateView.as_view(), name='update_stage'),
    # Puntos de Muestreo
    path('add_sample_point/<uuid:pk>/', SamplePointCreateView.as_view(), name='create_sample_point'),
    path('update_sample_point/<uuid:pk>/', SamplePointUpdateView.as_view(), name='update_sample_point')
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

luka/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.home.views import HomeView
from luka import settings as setting, settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", HomeView.as_view(), name='home'),
    path('user/', include('core.user.urls')),
    path('start/', include('core.start.urls')),
    path('login/', include('core.login.urls')),
    path('company/', include('core.company.urls')),
    path('reagent/', include('core.reagent.urls')),
    path('solution/', include('core.solution.urls')),
    path('laboratory/', include('core.laboratory.urls')),
    path('equipment/', include('core.equipment.urls')),
    # path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if setting.DEBUG:
    urlpatterns += static(setting.MEDIA_URL, document_root=setting.MEDIA_ROOT)

core/company/views/company/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.http import JsonResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DetailView

from core.company.forms import *
from core.company.models import *
from core.mixins import ValidatePermissionRequiredMixin


# Creación de Empresa
class CompanyCreateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, CreateView):
    model = Company
    form_class = CompanyForm
    template_name = 'company/create_company.html'
    permission_required = 'company.add_company'

    def dispatch(self, request, *args, **kwargs):
        self.object = None
        try:
            if Company.objects.exists():
                company = Company.objects.first()
                return redirect('company:company_detail', pk=company.id)
        except ObjectDoesNotExist:
            pass
        return super(CompanyCreateView, self).dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()
                if form.is_valid():
                    form.save()
                    messages.success(request, f'Empresa configurada satisfactoriamente!')
                else:
                    messages.error(request, form.errors)
            else:
                data['error'] = 'No ha ingresado datos en los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Perfil Empresa'
        context['entity'] = 'Perfil Empresa'
        context['action'] = 'add'
        context['div'] = '10'
        context['list_url'] = reverse_lazy('start:start')
        context['icon'] = 'bi bi-building-fill-add'
        return context


# Edición de Empresa
class CompanyUpdateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, UpdateView):
    model = Company
    form_class = CompanyForm
    template_name = 'company/create_company.html'
    permission_required = 'company.change_company'

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                if form.is_valid():
                    form.save()
                    messages.success(request, f'La Empresa se ha editado satisfactoriamente!')
                    # Return a direct redirect response instead of relying on client-side redirection
                    return redirect(self.get_context_data()['list_url'])
                else:
                    messages.error(request, form.errors)
                    data['error'] = form.errors
            else:
                data['error'] = 'No ha editado los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Editar Empresa'
        context['entity'] = 'Editar Información Empresa'
        context['action'] = 'edit'
        context['div'] = '10'
        context['list_url'] = reverse_lazy('company:company_detail', kwargs={'pk': self.kwargs['pk']})
        context['icon'] = 'bi bi-buildings-fill'
        return context


# Detalle de empresa por administrador
class CompanyDetailView(LoginRequiredMixin, ValidatePermissionRequiredMixin, DetailView):
    model = Company
    template_name = 'company/detail_company.html'
    permission_required = 'user.change_user'

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return super(CompanyDetailView, self).get_queryset()

    def logo(self):
        try:
            return Company.objects.first().get_logo()
        except ObjectDoesNotExist:
            return '{}{}'.format(STATIC_URL, 'img/empty.png')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Empresa'
        context['entity'] = 'Empresa'
        context['sites'] = Site.objects.filter(company_id=self.object.id)
        context['icon'] = 'bi bi-buildings-fill'
        context['company_logo'] = self.logo()
        return context

core/company/views/process/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView, UpdateView

from core.company.forms import ProcessForm, ProcessUpdateForm
from core.company.models import Process, Site
from core.mixins import ValidatePermissionRequiredMixin


# Creación de Proceso
class ProcessCreateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, CreateView):
    model = Process
    form_class = ProcessForm
    template_name = 'process/create_process.html'
    permission_required = 'company.add_company'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        self.object = None
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()
                if form.is_valid():
                    form.save()
                    messages.success(request, f'Proceso creado satisfactoriamente!')
                else:
                    messages.error(request, form.errors)
            else:
                data['error'] = 'No ha ingresado datos en los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'site': Site.objects.get(pk=self.kwargs.get('pk'))})
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action'] = 'add'
        context['entity'] = 'Creación de Proceso'
        context['class'] = 'col-md-8'
        return context


# Edición de Proceso
class ProcessUpdateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, UpdateView):
    model = Process
    form_class = ProcessUpdateForm
    template_name = 'process/create_process.html'
    permission_required = 'company.add_company'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                if form.is_valid():
                    form.save()
                    messages.success(request, f'Proceso editado satisfactoriamente!')
                else:
                    messages.error(request, form.errors)
                # return redirect(self.get_context_data()['list_url'])
            else:
                data['error'] = 'No ha ingresado datos en los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['entity'] = 'Edición de Proceso'
        context['action'] = 'edit'
        return context

core/company/views/sample_point/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView, UpdateView

from core.company.forms import SamplePointForm, SamplePointUpdateForm
from core.company.models import SamplePoint, Site
from core.mixins import ValidatePermissionRequiredMixin


# Creación de Puntos de Muestreo
class SamplePointCreateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, CreateView):
    model = SamplePoint
    form_class = SamplePointForm
    template_name = 'sample_point/create_sample_point.html'
    permission_required = 'company.add_company'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        self.object = None
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()
                if form.is_valid():
                    form.save()
                    messages.success(request, f'Punto de Muestreo creado satisfactoriamente!')
                else:
                    messages.error(request, 'Por favor corrija los errores: {}'.format(form.errors.as_json()))
            else:
                data['error'] = 'No ha ingresado datos en los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        site = Site.objects.get(pk=self.kwargs.get('pk'))
        kwargs.update({'site': site})
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action'] = 'add'
        context['entity'] = 'Creación de Punto de Muestreo'
        return context


# Edición de Puntos de Muestreo
class SamplePointUpdateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, UpdateView):
    model = SamplePoint
    form_class = SamplePointUpdateForm
    template_name = 'sample_point/create_sample_point.html'
    permission_required = 'company.add_company'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                if form.is_valid():
                    form.save()
                    messages.success(request, f'Punto de Muestreo editado satisfactoriamente!')
                else:
                    messages.error(request, 'Por favor corrija los errores: {}'.format(form.errors.as_json()))
            else:
                data['error'] = 'No ha ingresado datos en los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        sample = SamplePoint.objects.get(pk=self.kwargs.get('pk'))
        kwargs.update({'sample': sample})
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['entity'] = 'Edición de Punto de Muestreo'
        context['action'] = 'edit'
        return context

core/company/views/stage/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView, UpdateView

from core.company.forms import StageForm, StageUpdateForm
from core.company.models import Stage, Site
from core.mixins import ValidatePermissionRequiredMixin


# Creación de Etapas
class StageCreateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, CreateView):
    model = Stage
    form_class = StageForm
    template_name = 'stage/create_stage.html'
    permission_required = 'company.add_company'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        self.object = None
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()
                if form.is_valid():
                    form.save()
                    messages.success(request, f'Etapa creada satisfactoriamente!')
                else:
                    messages.error(request, 'Por favor corrija los errores: {}'.format(form.errors.as_json()))
            else:
                data['error'] = 'No ha ingresado datos en los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        site = Site.objects.get(pk=self.kwargs.get('pk'))
        kwargs.update({'site': site})
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action'] = 'add'
        context['entity'] = 'Creación de Etapa'
        return context


# Edición de Etapa
class StageUpdateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, UpdateView):
    model = Stage
    form_class = StageUpdateForm
    template_name = 'stage/create_stage.html'
    permission_required = 'company.add_company'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                if form.is_valid():
                    form.save()
                    messages.success(request, f'Etapa editada satisfactoriamente!')
                else:
                    messages.error(request, 'Por favor corrija los errores: {}'.format(form.errors.as_json()))
            else:
                data['error'] = 'No ha ingresado datos en los campos'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        stage = Stage.objects.get(pk=self.kwargs.get('pk'))
        kwargs.update({'stage': stage})
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['entity'] = 'Edición de Etapa'
        context['action'] = 'edit'
        return context

core/company/templates/site/create_site.html
{% extends 'create_two.html' %}

core/company/templates/site/detail_site.html
{% extends 'body.html' %}

{% load static %}


{% block head %}
    {% block head_list %}

    {% endblock %}
{% endblock %}

{% block content %}
    <div class="row" style="margin-bottom: 0;">
        <div class="col-md-4">
            <div class="tile" style="margin-bottom: 15px;">
                <div class="tile-title-w-btn">
                    <h3 class="title">Procesos</h3>
                    <p>
                        <a class="btn btn-primary icon-btn"
                           onclick="open_modal('{% url 'company:create_process' object.id %}')"><i
                                class="bi bi-plus-square me-2"></i>Nuevo</a>
                    </p>
                </div>
                <div class="tile-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Descripción</th>
                            <th>Estado</th>
                            <th>Acciones</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for process in processes %}
                            <tr>
                                <td>{{ process.process_name }}</td>
                                <td>
                                    {% if process.enable_process %}
                                        <span class="me-1 badge bg-primary">Activo</span>
                                    {% else %}
                                        <span class="me-1 badge bg-danger">Inactivo</span>
                                    {% endif %}
                                </td>
                                <td>
                                    <a onclick="open_modal('{% url 'company:update_process' process.id %}')"
                                       type="button" title="Editar">
                                        <i class="bi bi-pencil-square text-warning me-2"></i>
                                    </a>
                                </td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="3" class="text-center">
                                    No hay procesos asociados a esta planta.
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="tile">
                <div class="tile-title-w-btn">
                    <h3 class="title">Etapas</h3>
                    <p>
                        {% if processes %}
                            <a class="btn btn-primary icon-btn"
                               onclick="open_modal('{% url 'company:create_stage' object.id %}')"><i
                                    class="bi bi-plus-square me-2"></i>Nuevo</a>
                        {% endif %}
                    </p>
                </div>
                <div class="tile-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Etapa</th>
                            <th>Proceso</th>
                            <th>Estado</th>
                            <th>Acciones</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for stg in stages %}
                            <tr>
                                <td>{{ stg.stage_code }} {{ stg.stage_name }}</td>
                                <td>{{ stg.process }}</td>
                                <td>
                                    {% if stg.enable_stage %}
                                        <span class="me-1 badge bg-primary">Activo</span>
                                    {% else %}
                                        <span class="me-1 badge bg-danger">Inactivo</span>
                                    {% endif %}
                                </td>
                                <td>
                                    <a onclick="open_modal('{% url 'company:update_stage' stg.id %}')" title="Editar">
                                        <i class="bi bi-pencil-square text-warning me-2"></i>
                                    </a>
                                </td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="4" class="text-center">
                                    No hay etapas asociadas a esta planta.
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="tile">
                <div class="tile-title-w-btn">
                    <h3 class="title">Puntos de Muestreo</h3>
                    <p>
                        {% if stages %}
                            <a class="btn btn-primary icon-btn"
                               onclick="open_modal('{% url 'company:create_sample_point' object.id %}')"><i
                                    class="bi bi-plus-square me-2"></i>Nuevo</a>
                        {% endif %}
                    </p>
                </div>
                <div class="tile-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Punto de Muestreo</th>
                            <th>Etapa</th>
                            <th>Matriz</th>
                            <th>Versión</th>
                            <th>Estado</th>
                            <th>Acciones</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for sample in sample_point %}
                            <tr>
                                <td>{{ sample.sample_point_code }} {{ sample.sample_point_name }}</td>
                                <td>{{ sample.stage }}</td>
                                <td>{{ sample.sample_type }}</td>
                                <td>{{ sample.sample_point_version }}</td>
                                <td>
                                    {% if sample.enable_point %}
                                        <span class="me-1 badge bg-primary">Activo</span>
                                    {% else %}
                                        <span class="me-1 badge bg-danger">Inactivo</span>
                                    {% endif %}
                                </td>
                                <td>
                                    <a onclick="open_modal('{% url 'company:update_sample_point' sample.id %}')"
                                       title="Editar">
                                        <i class="bi bi-pencil-square text-warning me-2"></i>
                                    </a>
                                </td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="4" class="text-center">
                                    No hay puntos de muestreo asociados a esta planta.
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts_detail %}

    <script>
        // Initialize tooltips
        document.addEventListener("DOMContentLoaded", function () {
            // Inicializar tooltips
            var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'));
            var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
                return new bootstrap.Tooltip(tooltipTriggerEl);
            });
        });

        // Handle form submission in modal using vanilla JavaScript
        document.addEventListener('submit', function (e) {
            // Check if the form is inside a modal
            if (e.target.closest('.modal') && e.target.tagName === 'FORM') {
                e.preventDefault();
                var form = e.target;
                var url = form.getAttribute('action');
                var data = new FormData(form);

                // Use fetch API instead of $.ajax
                fetch(url, {
                    method: 'POST',
                    body: data
                })
                    .then(response => response.json())
                    .then(response => {
                        if (!response.hasOwnProperty('error')) {
                            // Close modal using Bootstrap 5 syntax
                            var modalElement = document.getElementById('modal_template');
                            var modalInstance = bootstrap.Modal.getInstance(modalElement);
                            modalInstance.hide();
                            // Reload page to show new data
                            location.reload();
                        } else {
                            // Show error message
                            alert(response.error);
                        }
                    })
                    .catch(error => {
                        console.error('Error:', error);
                        alert('Error en el envío del formulario');
                    });
            }
        });
    </script>

{% endblock %}

core/company/templates/site/list_site.html
{% extends 'list_one.html' %}
{% load static %}


{% block head_list %}
    <script src="{% static 'list_site.js' %}"></script>
{% endblock %}

{% block buttons %}
    <a href="{{ create_url }}" class="btn bg-gradient-dark mb-0"><i class="fa-solid fa-plus"></i> Nuevo</a>
{% endblock %}

{% block columns %}
    <tr>
        <th class="text-uppercase text-secondary text-center text-xs font-weight-bolder opacity-10" style="width:25%">Planta</th>
        <th class="text-uppercase text-secondary text-center text-xs font-weight-bolder opacity-10" style="width:15%">Dirección</th>
        <th class="text-uppercase text-secondary text-center text-xs font-weight-bolder opacity-10" style="width:20%">Ciudad</th>
        <th class="text-uppercase text-secondary text-center text-xs font-weight-bolder opacity-10" style="width:20%">País</th>
        <th class="text-uppercase text-secondary text-center text-xs font-weight-bolder opacity-10" style="width:10%">Activo</th>
        <th class="text-uppercase text-secondary text-center text-xs font-weight-bolder opacity-10" style="width:10%">Acciones</th>
    </tr>
{% endblock %}

{% block rows %}


{% endblock %}

{% block scripts_detail %}

{% endblock %}